apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: react-ci-cd-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy.send.timeout: "8"
    nginx.ingress.kubernetes.io/proxy.read.timeout: "8"
    nginx.ingress.kubernetes.io/proxy.connect.timeout: "8"
    nginx.ingress.kubernetes.io/service-upstream: "true"
#    nginx.ingress.kubernetes.io/rewrite: /$1

spec:
  ingressClassName: nginx
  rules:
    - host: ci-cd.react
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-ci-cd-service
                port:
                  number: 80

---
