apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - mongodb-repo.yaml
  - mongodb-release.yaml

configMapGenerator:
  - name: mongodb-custom-values
    files:
      - values.yaml # On pointe vers ton fichier
