apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongodb-repo.yaml
  - mongodb-release.yaml

configMapGenerator:
  - name: mongodb-custom-values
    files:
      - custom-values.yaml=./values.yaml # On pointe vers ton fichier
